version: "2"
networks: 
    app_bridge:
        driver: bridge
services:
    nginx: 
        image: nginx
        container_name: sudoku-solver-nginx-container
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        depends_on: 
            - sudoku_solver
        networks:
            - app_bridge

    sudoku_solver:
        image: siouija/sudoku-solver:48
        container_name: sudoku-solver-api-container
        restart: always
        networks: 
            - app_bridge
